name: Publish

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: "${{secrets.PUBLISH_PAT}}"

      - name: generate
        run: |
          date >> generated.txt
      - name: commit and push
        uses: devops-infra/action-commit-push@v1.0.3
        with: 
          github_token: "${{secrets.PUBLISH_PAT}}"  
          add_timestamp: true
          amend: false
          commit_prefix: "[AUTO]"
          commit_message: "Automatic commit"
          force: false
          force_with_lease: false
          no_edit: false