name: Publish

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - run: |
          date >> generated.txt
          # Note: the following account information will not work on GHES
          git config user.name "homberghp"
          git config user.email "pieter.van.den.hombergh@gmail.com"
          git add .
          git commit -m "generated"
